### ISSUE TITLE
global DS is deprecated

### ISSUE THREAD

**Issue by MartinMalinda** [aexmachina/ember-devtools#25]
On Ember 2.8 and later, devtools trigger this deprecation warning:
> DEPRECATION: Using the global version of DS is deprecated. Please either import the specific modules needed or `import DS from 'ember-data';`. [deprecation id: ember-data.global-ds]

**Comment by zzarcon** [comment]
This happens because the [ember-devtools initializer](https://github.com/aexmachina/ember-devtools/blob/master/app/initializers/ember-devtools.js#L3) accesses DS directly from the window scope. I think this is needed because the [instance initializer ember-devtools](https://github.com/aexmachina/ember-devtools/blob/master/app/instance-initializers/ember-devtools.js) depends on ember data to be ready?

@aexmachina can you check if this is still needed? maybe we can just get rid of the initializer?

I will happily do it, but Im not sure if my point is right.

**Comment by aexmachina** [comment]
@MartinMalinda thanks. That initializer is no longer required, have removed in v5.1.1.
